In [2]:
import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [3]:
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]# Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [14]:
import time

## Problem a)
A = np.array([
[0.582745, 0.48 , 0.10 , 0.  , 0.  ],
[0.48 , 1.044129, 0.46 , 0.10 , 0.  ],
[0.10 , 0.46 , 1.10431 , 0.44 , 0.10 ],
[0.  , 0.10 , 0.44 , 0.963889, 0.42 ],
[0.  , 0.  , 0.10 , 0.42 , 0.522565]], dtype=float)

b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

## Gauss-Sidel
x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 100
start = time.time() ##timer
solution_gauss, iterations_gauss = gauss_seidel(A, b, x0, tol, max_iterations)
end = time.time()

gauss_elapsed  = end - start


## Jacobi

x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 10000
start = time.time() ##timer
solution_jacobi, iterations_jacobi = jacobi(A, b, x0, tol, max_iterations)
end = time.time()

jacobi_elapsed  = end - start

print(f"Gauss-Sidel (matrix, iteration, elapsed):")
print(solution_gauss, iterations_gauss, gauss_elapsed, "seconds")
print()
print(f"Jacobi (matrix, iteration, elapsed):")
print(solution_jacobi, iterations_jacobi, jacobi_elapsed, "seconds")
print()
print(f"Real Solution:") 
print(np.linalg.solve(A, b))

Gauss-Sidel (matrix, iteration, elapsed):
[0.99999926 1.00000045 0.99999989 0.99999997 1.00000005] 20 0.001489877700805664 seconds

Jacobi (matrix, iteration, elapsed):
[1.0000005 1.0000005 1.0000005 1.0000005 1.0000005] 3462 0.17966437339782715 seconds

Real Solution:
[1. 1. 1. 1. 1.]


In [13]:
## Problem b)
A = np.array([[1, 1], [1, 1.0001]])

b = np.array([1, 1])




## Gauss-Sidel
x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 100000
start = time.time() ##timer
solution_gauss, iterations_gauss = gauss_seidel(A, b, x0, tol, max_iterations)
end = time.time()

gauss_elapsed  = end - start


## Jacobi

x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 10000000
start = time.time() ##timer
solution_jacobi, iterations_jacobi = jacobi(A, b, x0, tol, max_iterations)
end = time.time()

jacobi_elapsed  = end - start

print(f"Gauss-Sidel (matrix, iteration, elapsed):")
print(solution_gauss, iterations_gauss, gauss_elapsed, "seconds")
print()
print(f"Jacobi (matrix, iteration, elapsed):")
print(solution_jacobi, iterations_jacobi, jacobi_elapsed, "seconds")
print()
print(f"Real Solution:") 
print(np.linalg.solve(A, b))

Gauss-Sidel (matrix, iteration, elapsed):
[1. 0.] 1 0.0002655982971191406 seconds

Jacobi (matrix, iteration, elapsed):
[0.999999 0.      ] 276325 8.783317565917969 seconds

Real Solution:
[1. 0.]


In [10]:
## Problem c)
A = np.array([[1, 1], [1, 1.0001]])

b = np.array([1, 1.0001])




## Gauss-Sidel
x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 1000000
start = time.time() ##timer
solution_gauss, iterations_gauss = gauss_seidel(A, b, x0, tol, max_iterations)
end = time.time()

gauss_elapsed  = end - start


## Jacobi

x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 1000000
start = time.time() ##timer
solution_jacobi, iterations_jacobi = jacobi(A, b, x0, tol, max_iterations)
end = time.time()

jacobi_elapsed  = end - start

print(f"Gauss-Sidel (matrix, iteration, elapsed):")
print(solution_gauss, iterations_gauss, gauss_elapsed, "seconds")
print()
print(f"Jacobi (matrix, iteration, elapsed):")
print(solution_jacobi, iterations_jacobi, jacobi_elapsed, "seconds")
print()
print(f"Real Solution:") 
print(np.linalg.solve(A, b))

Gauss-Sidel (matrix, iteration, elapsed):
[0.009999 0.990002] 46055 0.8889100551605225 seconds

Jacobi (matrix, iteration, elapsed):
[9.9990135e-07 1.0000000e+00] 276326 6.136561870574951 seconds

Real Solution:
[0. 1.]


In [ ]:
##In all 3 scenarios, Gauss-Sidel is much faster in both convergence and computing time than Jacobi.