In [8]:
import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [9]:
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]# Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [29]:
import time

## Problem a)
A = np.array([
    [10, -1,   2,   0,  0],
    [-1, 11,  -1,   3,  0],
    [2,  -1,  10,   1,  0],
    [0,   3,  -1,   8, -2],
    [0,   0,   0,  -2,  9]
], dtype=float)
b = np.array(
    [14, 22, 33, 26, 22], dtype=float
)


## Gauss-Sidel
x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 100
start = time.time() ##timer
solution_gauss, iterations_gauss = gauss_seidel(A, b, x0, tol, max_iterations)
end = time.time()

gauss_elapsed  = end - start


## Jacobi

x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 100
start = time.time() ##timer
solution_jacobi, iterations_jacobi = jacobi(A, b, x0, tol, max_iterations)
end = time.time()

jacobi_elapsed  = end - start

print(f"Gauss-Sidel (matrix, iteration, elapsed):")
print(solution_gauss, iterations_gauss, gauss_elapsed, "seconds")
print()
print(f"Jacobi (matrix, iteration, elapsed):")
print(solution_jacobi, iterations_jacobi, jacobi_elapsed, "seconds")
print()
print(f"Real Solution:") 
print(np.linalg.solve(A, b))

Gauss-Sidel (matrix, iteration, elapsed):
[0.95876418 1.26473215 2.83854518 3.96175203 3.32483379] 10 0.0007541179656982422 seconds

Jacobi (matrix, iteration, elapsed):
[0.95876415 1.26473263 2.83854549 3.9617514  3.32483342] 15 0.0011370182037353516 seconds

Real Solution:
[0.95876418 1.26473211 2.83854517 3.96175205 3.32483379]


In [30]:
## Problem b)
A = np.array([
    [1, 2, 3, 0, 0], 
    [2, 1, 2, 3, 0], 
    [3, 2, 1, 2, 3], 
    [0, 3, 2, 1, 2], 
    [0, 0, 3, 2, 1]
], dtype=float)
b = np.array(
    [14, 22, 33, 26, 22], dtype=float
)


## Gauss-Sidel
x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 1000
start = time.time() ##timer
solution_gauss, iterations_gauss = gauss_seidel(A, b, x0, tol, max_iterations)
end = time.time()

gauss_elapsed  = end - start


## Jacobi

x0 = np.zeros(len(b))
tol = 1e-6
max_iterations = 1000
start = time.time() ##timer
solution_jacobi, iterations_jacobi = jacobi(A, b, x0, tol, max_iterations)
end = time.time()

jacobi_elapsed  = end - start

print(f"Gauss-Sidel (matrix, iteration, elapsed):")
print(solution_gauss, iterations_gauss, gauss_elapsed, "seconds")
print()
print(f"Jacobi (matrix, iteration, elapsed):")
print(solution_jacobi, iterations_jacobi, jacobi_elapsed, "seconds")
print()
print(f"Real Solution:") 
print(np.linalg.solve(A, b))

Gauss-Sidel (matrix, iteration, elapsed):
[nan nan nan nan nan] 1000 0.05491447448730469 seconds

Jacobi (matrix, iteration, elapsed):
[nan nan nan nan nan] 1000 0.0527801513671875 seconds

Real Solution:
[1. 2. 3. 4. 5.]


<ipython-input-9-f68e5aeb04da>:7: RuntimeWarning: overflow encountered in double_scalars
  s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
<ipython-input-9-f68e5aeb04da>:8: RuntimeWarning: overflow encountered in double_scalars
  s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
<ipython-input-9-f68e5aeb04da>:8: RuntimeWarning: invalid value encountered in double_scalars
  s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values


In [31]:
##In problem a), The Gauss-Sidel method converged in fewer iterations, was generally more accurate, and took less time
##to compute than the Jacobi method. This makes sense, as the Gauss-Sidel method is generally more efficient than the
##Jacobi method, even if less intuitive.

##In problem b), neither method gave a coherent answer, even with the max iterations set to 1000. It makes sense that
##neither iterative method converged, since matrix A is not diagonally-dominant.